function showcontent() {
    let whatFase = document.getElementById('fase').value;
    switch (whatFase){
        case('Leerjaar 1 - Periode 1.1 - fase 1'): {
            document.getElementById('content').innerHTML = '<table class="table table-bordered table-striped color-yellow"><thead><tr><th class="centerText" colspan="2">Leerjaar 1 - Periode 1.1 - Oriëntatie</th></tr></thead></table><br><table class="table table-bordered table-striped color-yellow"><thead><tr><th>Vakken</th><th>Aantal uren per week</th></tr></thead><tbody><tr><td>Theoretisch programmeren<p class="text">test4502</p></td><td>2-uren</td></tr><tr><td>Programmeren</td><td>8-uren</td></tr><tr><td>Project</td><td>6-uren</td></tr><tr><td>Werkveld orientatie</td><td>3-uren</td></tr><tr><td>Burgerschap</td><td>1-uren</td></tr><tr><td>Studieloopbaan begeleiding</td><td>1-uren</td></tr><tr><td>Nederlands</td><td>2-uren</td></tr><tr><td>Engels</td><td>1-uren</td></tr><tr><td>Rekenen</td><td>2-uren</td></tr><tr><th>Totaal uren</th><th>26</th></tr></tbody></table>\n';
            document.body.style.background = "#FFF3C9";

        }break;
        case('Leerjaar 1 - Periode 1.2 - fase 1'): {
            document.getElementById('content').innerHTML = '<table class="table table-bordered table-striped color-yellow"><thead><tr><th class="centerText" colspan="2">Leerjaar 1 - Periode 1.2 - Oriëntatie</th></tr></thead></table><br><table class="table table-bordered table-striped color-yellow"><thead><tr><th>Vakken</th><th>Aantal uren per week</th></tr></thead><tbody><tr><td>Theoretisch programmeren<p class="text">test4502</p></td><td>2-uren</td></tr><tr><td>Programmeren</td><td>8-uren</td></tr><tr><td>Project</td><td>6-uren</td></tr><tr><td>Werkveld orientatie</td><td>3-uren</td></tr><tr><td>Burgerschap</td><td>1-uren</td></tr><tr><td>Studieloopbaan begeleiding</td><td>1-uren</td></tr><tr><td>Nederlands</td><td>2-uren</td></tr><tr><td>Engels</td><td>1-uren</td></tr><tr><td>Rekenen</td><td>2-uren</td></tr><tr><th>Totaal uren</th><th>26</th></tr></tbody></table>\n';
            document.body.style.background = "#FFF3C9";

        }break;
        case('Leerjaar 2 - Periode 1.3 - fase 2'):{
            document.getElementById('content').innerHTML = '<table class="table table-bordered table-striped color-lightblue"> <thead> <tr> <th class="centerText" colspan="2">Leerjaar 2 - Periode 1.3 - Basis</th> </tr></thead></table><br><table class="table table-bordered table-striped color-lightblue"> <thead><tr> <th>Vakken</th> <th>Aantal uren per week</th> </tr> </thead> <tbody> <tr> <td>Theoretisch programmeren <div class="text">test<p></p> </div> </td> <td>2-uren</td> </tr> <tr> <td>Front-end development</td> <td>4-uren</td> </tr> <tr> <td>Back-end development</td> <td>4-uren</td> </tr> <tr> <td>Project</td> <td>4-uren</td> </tr> <tr> <td>User experience design</td> <td>2-uren</td> </tr> <tr> <td>Werkveld orientatie</td> <td>2-uren</td> </tr> <tr> <td>Burgerschap</td> <td>1-uren</td> </tr> <tr> <td>Studieloopbaan begeleiding</td> <td>1-uren</td> </tr> <tr> <td>Nederlands</td> <td>1-uren</td> </tr> <tr> <td>Engels</td> <td>2-uren</td> </tr> <tr> <td>Rekenen</td> <td>2-uren</td> </tr> <tr> <th>Totaal uren</th> <th>26</th> </tr> </tbody> </table>';
            document.body.style.background = "#E8EDF4";

        }break;
        case('Leerjaar 2 - Periode 1.4 - fase 2'):{
            document.getElementById('content').innerHTML = '<table class="table table-bordered table-striped color-lightblue"> <thead> <tr> <th class="centerText" colspan="2">Leerjaar 2 - Periode 1.4 - Basis</th> </tr> </thead></table><br><table class="table table-bordered table-striped color-lightblue"> <thead> <tr> <th>Vakken</th> <th>Aantal uren per week</th> </tr> </thead> <tbody> <tr> <td>Theoretisch programmeren <div class="text">test<p></p> </div> </td> <td>2-uren</td> </tr> <tr> <td>Front-end development</td> <td>4-uren</td> </tr> <tr> <td>Back-end development</td> <td>4-uren</td> </tr> <tr> <td>Project</td> <td>4-uren</td> </tr> <tr> <td>User experience design</td> <td>2-uren</td> </tr> <tr> <td>Werkveld orientatie</td> <td>2-uren</td> </tr> <tr> <td>Burgerschap</td> <td>1-uren</td> </tr> <tr> <td>Studieloopbaan begeleiding</td> <td>1-uren</td> </tr> <tr> <td>Nederlands</td> <td>1-uren</td> </tr> <tr> <td>Engels</td> <td>2-uren</td> </tr> <tr> <td>Rekenen</td> <td>2-uren</td> </tr> <tr> <th>Totaal uren</th> <th>26</th> </tr> </tbody> </table>';
            document.body.style.background = "#E8EDF4";

        }break;
        case('Leerjaar 2 - Periode 2.1 - fase 2'):{
            document.getElementById('content').innerHTML = '<table class="table table-bordered table-striped color-lightblue"> <thead> <tr> <th class="centerText" colspan="2">Leerjaar 2 - Periode 2.1 - Basis</th> </tr> </thead></table><br><table class="table table-bordered table-striped color-lightblue"> <thead> <tr> <th>Vakken</th> <th>Aantal uren per week</th> </tr> </thead> <tbody> <tr> <td>Keuzedeel front-end development</td> <td>2-uren</td> </tr> <tr> <td>Keuzedeel veilig programmeren</td> <td>2-uren</td> </tr> <tr> <td>Front-end development</td> <td>2-uren</td> </tr> <tr> <td>Back-end development</td> <td>3-uren</td> </tr> <tr> <td>Content managment systemen</td> <td>2-uren</td> </tr> <tr> <td>Inter disciplinair project</td> <td>6-uren</td> </tr> <tr> <td>Projectmatig werken</td> <td>1-uren</td> </tr> <tr> <td>Stagebegeleiding</td> <td>1-uren</td> </tr> <tr> <td>Studieloopbaan begeleiding</td> <td>1-uren</td> </tr> <tr> <td>Nederlands</td> <td>2-uren</td> </tr> <tr> <td>Engels</td> <td>2-uren</td> </tr> <tr> <td>Rekenen</td> <td>2-uren</td> </tr> <tr> <th>Totaal uren</th> <th>26</th> </tr> </tbody> </table>';
            document.body.style.background = "#E8EDF4";

        }break;
        case('Leerjaar 2 - Periode 2.2 - fase 3'):{
            document.getElementById('content').innerHTML = '<table class="table table-bordered table-striped color-terques"> <thead> <tr> <th class="centerText" colspan="2">Leerjaar 2 - Periode 2.2 - Verdieping</th> </tr></thead></table><br><table class="table table-bordered table-striped color-terques"> <thead> <tr> <th>Vakken</th> <th>Aantal uren per week</th> </tr> </thead> <tbody> <tr> <td>Keuzedeel front-end development</td> <td>2-uren</td> </tr> <tr> <td>Keuzedeel veilig programmeren</td> <td>2-uren</td> </tr> <tr> <td>Front-end development</td> <td>2-uren</td> </tr> <tr> <td>Back-end development</td> <td>3-uren</td> </tr> <tr> <td>Content managment systemen</td> <td>2-uren</td> </tr> <tr> <td>Inter disciplinair project</td> <td>6-uren</td> </tr> <tr> <td>Projectmatig werken</td> <td>1-uren</td> </tr> <tr> <td>Stagebegeleiding</td> <td>1-uren</td> </tr> <tr> <td>Studieloopbaan begeleiding</td> <td>1-uren</td> </tr> <tr> <td>Nederlands</td> <td>2-uren</td> </tr> <tr> <td>Engels</td> <td>2-uren</td> </tr> <tr> <td>Rekenen</td> <td>2-uren</td> </tr> <tr> <th>Totaal uren</th> <th>26</th> </tr> </tbody> </table>';
            document.body.style.background = "#EDF4F2";

        }break;
        case('Leerjaar 2 - Periode 2.3 - fase 3/4'):{
            document.getElementById('content').innerHTML = '<table class="table table-bordered table-striped color-terques"> <thead> <tr> <th class="centerText" colspan="2">Leerjaar 3 - Periode 2.3 - Verdieping</th> <th class="centerText" style="background-color: #BF99D8" colspan="1">Fase 4 - Stage</th> </tr></thead></table><br><table class="table table-bordered table-striped color-terques"> <thead><tr> <th>Vakken</th> <th>Aantal uren op vrijdag</th> <th style="background-color: #BF99D8">Vakken</th> </tr> </thead> <tbody> <tr> <td>Keuze 3 Mobiel app development of Ondernemen</td> <td>1-uren</td> <td style=" background-color: #BF99D8">BPV</td> </tr> <tr> <td>Persoonlijke ontwikkeling</td> <td>1-uren</td> <td style="background-color: #BF99D8"></td> </tr> <tr> <td>Studieloopbaan begeleiding</td> <td>1-uren</td> <td style="background-color: #BF99D8"></td> </tr> <tr> <td>Nederlands</td> <td>1-uren</td> <td style="background-color: #BF99D8"></td> </tr> <tr> <td>Engels</td> <td>1-uren</td> <td style="background-color: #BF99D8"></td> </tr> <tr> <td>Rekenen</td> <td>1-uren</td> <td style="background-color: #BF99D8"></td> </tr> <tr> <th>Totaal uren</th> <th>6</th> <th style="background-color: #BF99D8">maandag t/m donderdag</th> </tr> </tbody> </table>';
            document.body.style.background = "#EDF4F2";

        }break;
        case('Leerjaar 2 - Periode 2.4 - fase 3/4'):{
            document.getElementById('content').innerHTML = '<table class="table table-bordered table-striped color-terques"> <thead> <tr> <th class="centerText" colspan="2">Leerjaar 3 - Periode 2.4 - Verdieping</th> <th class="centerText" style="background-color: #BF99D8" colspan="1">Fase 4 - Stage</th> </tr> </thead></table><br><table class="table table-bordered table-striped color-terques"> <thead> <tr><tr> <th>Vakken</th> <th>Aantal uren op vrijdag</th> <th style="background-color: #BF99D8">Vakken</th> </tr> </thead> <tbody> <tr> <td>Keuze 3 Mobiel app development of Ondernemen</td> <td>1-uren</td> <td style=" background-color: #BF99D8">BPV</td> </tr> <tr> <td>Persoonlijke ontwikkeling</td> <td>1-uren</td> <td style="background-color: #BF99D8"></td> </tr> <tr> <td>Studieloopbaan begeleiding</td> <td>1-uren</td> <td style="background-color: #BF99D8"></td> </tr> <tr> <td>Nederlands</td> <td>1-uren</td> <td style="background-color: #BF99D8"></td> </tr> <tr> <td>Engels</td> <td>1-uren</td> <td style="background-color: #BF99D8"></td> </tr> <tr> <td>Rekenen</td> <td>1-uren</td> <td style="background-color: #BF99D8"></td> </tr> <tr> <th>Totaal uren</th> <th>6</th> <th style="background-color: #BF99D8">maandag t/m donderdag</th> </tr> </tbody> </table>';
            document.body.style.background = "#EDF4F2";

        }break;
        case('Leerjaar 3 - Periode 3.1 - fase 3/4'):{
            document.getElementById('content').innerHTML = '<table class="table table-bordered table-striped color-terques"> <thead> <tr> <th class="centerText" colspan="2">Leerjaar 3 - Periode 3.1 - Verdieping</th> <th class="centerText" style="background-color: #BF99D8" colspan="1">Fase 4 - Stage</th> </tr></thead></table><br> <table class="table table-bordered table-striped color-terques"> <thead> <tr><tr> <th>Vakken</th> <th>Aantal uren op vrijdag</th> <th style="background-color: #BF99D8">Vakken</th> </tr> </thead> <tbody> <tr> <td>Keuze 3 Mobiel app development of Ondernemen</td> <td>4-uren</td> <td style="background-color: #BF99D8">BPV</td> </tr> <tr> <td>Persoonlijke ontwikkeling</td> <td>1-uren</td> <td style="background-color: #BF99D8"></td> </tr> <tr> <td>Studieloopbaan begeleiding</td> <td>1-uren</td> <td style="background-color: #BF99D8"></td> </tr> <tr> <th>Totaal uren</th> <th>6</th> <th style="background-color: #BF99D8">maandag t/m donderdag</th> </tr> </tbody> </table>';
            document.body.style.background = "#EDF4F2";

        }break;
        case('Leerjaar 3 - Periode 3.2 - fase 3/4'):{
            document.getElementById('content').innerHTML = '<table class="table table-bordered table-striped color-terques"> <thead> <tr> <th class="centerText" colspan="2">Leerjaar 3 - Periode 3.2 - Verdieping</th> <th class="centerText" style="background-color: #BF99D8" colspan="1">Fase 4 - Stage</th> </tr> </thead></table><br><table class="table table-bordered table-striped color-terques"> <thead> <tr><tr> <th>Vakken</th> <th>Aantal uren op vrijdag</th> <th style="background-color: #BF99D8">Vakken</th> </tr> </thead> <tbody> <tr> <td>Keuze 3 Mobiel app development of Ondernemen</td> <td>4-uren</td> <td style="background-color: #BF99D8">BPV</td> </tr> <tr> <td>Persoonlijke ontwikkeling</td> <td>1-uren</td> <td style="background-color: #BF99D8"></td> </tr> <tr> <td>Studieloopbaan begeleiding</td> <td>1-uren</td> <td style="background-color: #BF99D8"></td> </tr> <tr> <th>Totaal uren</th> <th>6</th> <th style="background-color: #BF99D8">maandag t/m donderdag</th> </tr> </tbody> </table>';
            document.body.style.background = "#EDF4F2";

        }break;
        case('Leerjaar 3 - Periode 3.3 - fase 5'):{
            document.getElementById('content').innerHTML = '<table class="table table-bordered table-striped color-red"> <thead> <tr> <th class="centerText" colspan="2">Leerjaar 3 - Periode 3.3 - Examen</th> </tr></thead></table><br><table class="table table-bordered table-striped color-red"> <thead> <tr> <tr> <th>Vakken</th> <th>Aantal uren op vrijdag</th> </tr> </thead> <tbody> <tr> <td>Examen proeve van bekwaamheid</td> <td>22-uren</td> </tr> <tr> <td>Persoonlijke ontwikkeling</td> <td>1-uren</td> </tr> <tr> <td>Studieloopbaan begeleiding</td> <td>1-uren</td> </tr> <tr> <td>Nederlands</td> <td>1-uren</td> </tr> <tr> <td>Engels</td> <td>1-uren</td> </tr> <tr> <th>Totaal uren</th> <th>26</th> </tr> </tbody> </table>';
            document.body.style.background = "#FFEDEA";
        }break;
        case('Leerjaar 3 - Periode 3.4 - fase 5'):{
            document.getElementById('content').innerHTML = '<table class="table table-bordered table-striped color-red"> <thead> <tr> <th class="centerText" colspan="2">Leerjaar 3 - Periode 3.4 - Examen</th> </tr></thead></table><br> <table class="table table-bordered table-striped color-red"> <thead> <tr><tr> <th>Vakken</th> <th>Aantal uren op vrijdag</th> </tr> </thead> <tbody> <tr> <td>Examen proeve van bekwaamheid</td> <td>22-uren</td> </tr> <tr> <td>Persoonlijke ontwikkeling</td> <td>1-uren</td> </tr> <tr> <td>Studieloopbaan begeleiding</td> <td>1-uren</td> </tr> <tr> <td>Nederlands</td> <td>1-uren</td> </tr> <tr> <td>Engels</td> <td>1-uren</td> </tr> <tr> <th>Totaal uren</th> <th>26</th> </tr> </tbody> </table>';
            document.body.style.background = "#FFEDEA";
        }break;
        case('Kies Periode'):{
            document.getElementById('content').innerHTML = '        <h3>Kies een periode in het dropdown menu hierboven </h3>\n'
        }

    }}


